// InventoryManagement/Service/ReportService.js
const dailyReportRepository = require('../Repository/Report');
const saleRepository = require('../Repository/Sale');

class ReportService {
  // Pulls every completed sale for the given date, sums the totals,
  // and saves that as a DailyReport row.
  async generateDailyReport({ date, generatedById }) {
    if (!date) {
      throw new Error('Report date is required');
    }
    if (!generatedById) {
      throw new Error('Generated by user ID is required');
    }

    const reportDate = new Date(date);
    if (isNaN(reportDate.getTime())) {
      throw new Error('Invalid date provided');
    }

    // Prevent generating reports for future dates
    const now = new Date();
    const todayStart = new Date(now);
    todayStart.setHours(0, 0, 0, 0);
    if (reportDate > todayStart) {
      throw new Error('Cannot generate report for a future date');
    }

    const startOfDay = new Date(reportDate);
    startOfDay.setHours(0, 0, 0, 0);

    const endOfDay = new Date(reportDate);
    endOfDay.setHours(23, 59, 59, 999);

    const sales = await saleRepository.findByDateRange(startOfDay, endOfDay);
    const completedSales = sales.filter((s) => s.status === 'completed');

    const totalSalesAmount = completedSales.reduce(
      (sum, sale) => sum + Number(sale.totalAmount),
      0
    );

    // reportDate is @unique in the schema, so this will fail if a report
    // for this exact date already exists — decide whether to update
    // instead if you re-run this for the same day.
    return dailyReportRepository.create({
      reportDate: startOfDay,
      generatedById,
      totalSalesAmount,
    });
  }

  // Returns null if no report exists for the given date
  async getReportByDate(date) {
    if (!date) return null;
    const day = new Date(date);
    if (isNaN(day.getTime())) return null;
    day.setHours(0, 0, 0, 0);
    return dailyReportRepository.findByDate(day);
  }

  async listReports(startDate, endDate) {
    return dailyReportRepository.findByDateRange(startDate, endDate);
  }
}

module.exports = new ReportService();