// InventoryManagement/Service/ReportService.js
const dailyReportRepository = require('../Repository/Report');
const saleRepository = require('../Repository/Sale');
const { ValidationError } = require('../../errors');

class ReportService {
  // Pulls every completed sale for the given date, sums the totals,
  // and saves that as a DailyReport row.
  // All date boundaries use UTC to be consistent regardless of server timezone.
  async generateDailyReport({ date, generatedById }) {
    if (!date) {
      throw new ValidationError('Report date is required');
    }
    if (!generatedById) {
      throw new ValidationError('Generated by user ID is required');
    }

    const reportDate = new Date(date);
    if (isNaN(reportDate.getTime())) {
      throw new ValidationError('Invalid date provided');
    }

    // Prevent generating reports for future dates.
    // Compare calendar dates (YYYY-MM-DD) in UTC to avoid timezone issues.
    // Date strings like "2026-10-06" parse as UTC midnight, so we extract
    // the UTC date portion for both dates and compare as strings.
    const reportDateUTC = reportDate.toISOString().split('T')[0]; // "YYYY-MM-DD" in UTC
    const todayUTC = new Date().toISOString().split('T')[0];       // "YYYY-MM-DD" in UTC
    if (reportDateUTC > todayUTC) {
      throw new ValidationError('Cannot generate report for a future date');
    }

    // Use UTC for all date boundaries to be consistent regardless of server timezone.
    // reportDate at UTC midnight
    const startOfDay = new Date(reportDate);
    startOfDay.setUTCHours(0, 0, 0, 0);

    // End of day in UTC
    const endOfDay = new Date(reportDate);
    endOfDay.setUTCHours(23, 59, 59, 999);

    const sales = await saleRepository.findByDateRange(startOfDay, endOfDay);
    const completedSales = sales.filter((s) => s.status === 'completed');

    const totalSalesAmount = completedSales.reduce(
      (sum, sale) => sum + Number(sale.totalAmount),
      0
    );

    // Store reportDate at UTC midnight (not local midnight)
    // This ensures the unique constraint works correctly regardless of server timezone.
    const reportDateAtMidnight = new Date(reportDate);
    reportDateAtMidnight.setUTCHours(0, 0, 0, 0);

    return dailyReportRepository.create({
      reportDate: reportDateAtMidnight,
      generatedById,
      totalSalesAmount,
    });
  }

  // Returns null if no report exists for the given date
  async getReportByDate(date) {
    if (!date) return null;
    const day = new Date(date);
    if (isNaN(day.getTime())) return null;
    day.setUTCHours(0, 0, 0, 0);
    return dailyReportRepository.findByDate(day);
  }

  async listReports(startDate, endDate) {
    return dailyReportRepository.findByDateRange(startDate, endDate);
  }
}

module.exports = new ReportService();